[package]
name = "anharu-calculator-project"
version = "0.1.0"
authors = ["Anharu <haruan2394@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
[build-dependencies]
peg = { version = "0.5" }
